language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: '5.4'
        - php: '5.5'
        - php: '5.6'
        - php: '7.0'
        - php: '7.1'

before_install:
    - phpenv config-rm xdebug.ini
    - wget https://phar.phpunit.de/phpunit-6.3.phar
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then curl -LSs https://box-project.github.io/box2/installer.php | php; fi;

install:
    - composer update --no-interaction --prefer-dist
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then php box.phar build; fi;

script:
    - php phpunit-6.3.phar

deploy:
    provider: releases
    api_key:
        secure: Oq9TAPQZqnjxhbprWZQE64GhK4vxBHjvcMkS9dkbkCJQVz8cSqGxZOFqMOHulraFs2IX9PLeplrZReFMT630KkMNf74mkTtL9WMuaMJV0bbUPY+X7YpDGlLNNU7OA9Rxjr3y68x1jVxD6mLSlCFZP00qvmYRlOE1i2ltjO7L5Sw=
    file: schema.phar
    skip_cleanup: true
    on:
      tags: true
      repo: api-platform/schema-generator
      php:  '7.1'
