language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: '5.4'
        - php: '5.5'
        - php: '5.6'
        - php: '7.0'
        - php: 'hhvm'

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
    - curl -LSs https://box-project.github.io/box2/installer.php | php

install:
    - composer update --no-interaction --prefer-dist
    - php box.phar build

script:
    - phpunit
    - tests/run-tests.sh

deploy:
    provider: releases
    api_key:
        secure: Oq9TAPQZqnjxhbprWZQE64GhK4vxBHjvcMkS9dkbkCJQVz8cSqGxZOFqMOHulraFs2IX9PLeplrZReFMT630KkMNf74mkTtL9WMuaMJV0bbUPY+X7YpDGlLNNU7OA9Rxjr3y68x1jVxD6mLSlCFZP00qvmYRlOE1i2ltjO7L5Sw=
    file: schema.phar
    skip_cleanup: true
    on:
      tags: true
      repo: api-platform/schema-generator
