language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - tests/run-tests.sh
