language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install --dev --prefer-source

script:
  - php vendor/bin/schema.php .
  - php vendor/bin/schema.php . vendor/dunglas/php-schema.org-model/examples/config/lechoppe.yml