#
# (c) Kévin Dunglas <dunglas@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

header: |
  /*
   * This file is part of the L'Échoppe package.
   *
   * (c) Kévin Dunglas <dunglas@gmail.com>
   *
   * For the full copyright and license information, please view the LICENSE
   * file that was distributed with this source code.
   */
namespace: Echoppe\CoreBundle\Entity
#namespaces:
#  interface: Echoppe\CoreBundle\Model
#  entity: Echoppe\CoreBundle\Entity
author: Kévin Dunglas <dunglas@gmail.com>
checkIsGoodRelations: true
types:
  Thing:
    properties:
      name: ~
      description: ~
      image: ~
  Product:
    properties:
      brand: ~
      color: ~
      depth: ~
      gtin13: ~
      gtin14: ~
      gtin8: ~
      height: ~
      itemCondition: ~
      mpn: ~
      offers: ~
      productId: ~
      releaseDate: ~
      sku: ~
      weight: ~
      width: ~
  Brand:
    parent: Thing
    properties:
      logo: { range: ImageObject }
  ImageObject:
    properties:
      caption: ~
  QuantitativeValue:
    properties:
      maxValue: ~
      minValue: ~
      unitCode: ~
      value: ~
  ProductModel:
    properties:
      isVariantOf: ~
  SomeProducts:
    properties:
      inventoryLevel: ~
  Offer:
    parent: Thing
    properties:
      acceptedPaymentMethod: ~
      addOn: ~
      availability: ~
      availabilityStarts: ~
      availabilityEnds: ~
      availableDeliveryMethod: ~
      category: { range: Text }
      deliveryLeadTime: ~
      eligibleCustomerType: ~
      eligibleDuration: ~
      eligibleQuantity: ~
      eligibleRegion: ~
      eligibleTransactionVolume: ~
      includesObject: ~
      inventoryLevel: ~
      itemCondition: ~
      priceSpecification: ~
      validFrom: ~
      validThrough: ~
#      warranty: ~
  StructuredValue:
      parent: Thing
  PriceSpecification: ~
  DeliveryChargeSpecification: ~
  PaymentChargeSpecification: ~
  UnitPriceSpecification:
    properties: { }
  TypeAndQuantityNode: ~
  OfferItemCondition:
    parent: false
  PaymentMethod:
    parent: false
  ItemAvailability:
    parent: false
  DeliveryMethod:
    parent: false
  BusinessEntityType:
    parent: false
#  WarrantyPromise: ~
#  WarrantyScope:
#    parent: false
  MediaObject: ~
  CreativeWork: ~